<?php
define('EMAILKEY', '47fd00bd8d6a031b8293dab823fb51edb33e5979');
define('EMAIL', 'multiplica@uebster.com');
define('JSON_SUPPORT', '1');
define('SITENAME', 'Multiplica');
define('SITEDESC', '');
define('USER', 'root');
define('PASS', '');
define('DATABASE', 'site-multiplica');
define('HOST', 'localhost');
define('PRE', 'mult_');
define('DEV', 'on');
define('LOCALHOST', true);
define('PROTOCOL', 'http://');
define('WWW', '');
define('DOMINIO', 'site-multiplica');
define('SITESUB', '');
define('HOME', 'http://localhost/site-multiplica/');
define('PATH_HOME', 'C:/wamp64/www\site-multiplica/');
define('LOGO', 'uploads/image/2018/07/logo.jpg');
define('FAVICON', 'uploads/image/2018/07/favicon-multiplica.png');
define('VERSION', '1.78');
define('VENDOR', 'vendor/conn/');
define('DEV_PATH', (DOMINIO === 'site-multiplica' ? "" : VENDOR . "site-multiplica/"));
